<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Dhruba" ignored="0" name="Test SauceNode2" tests="2" failures="1" timestamp="25 Nov 2018 02:03:41 GMT" time="28.372" errors="0">
  <testcase name="closing" time="0.026" classname="sauceLabTesting.SauceNode2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at sauceLabTesting.SauceNode2.closing(SauceNode2.java:44)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- closing -->
  <testcase name="initialize" time="28.284" classname="sauceLabTesting.SauceNode2"/>
</testsuite> <!-- Test SauceNode2 -->
